### ISSUE TITLE
Doesn't work on macOS Catalina

### ISSUE THREAD

**Issue by skibitsky** [nikitavoloboev/alfred-web-searches#23]
## Bug Summary 🐞
When calling workflow from extarnal trigger or keyword, I receive this window:
![Safari 2019-10-09 at 09 17 50@2x](https://user-images.githubusercontent.com/15127974/66456240-c5ac7e00-ea75-11e9-96dc-56c3e0eb784f.png)

I have the Gatekeeper disabled.
macOS v10.15

**Comment by nikivdev** [comment]
That's not good. If you go to Security & Privacy and system prefs, it sometimes gets a prompt here you have to accept:

![2019-10-09 at 10 43](https://user-images.githubusercontent.com/6391776/66470500-9ac82700-ea81-11e9-8aae-bc3c6cedebf0.png)

Let me know if that works. If it doesn't I have no idea.

**Comment by skibitsky** [comment]
It doesn't appear here, @nikitavoloboev 

Moreover, I have **"Allow apps downloaded from:"** set to **"Anywhere"**
<img width="565" alt="CleanShot 2019-10-09 at 13 07 54@2x" src="https://user-images.githubusercontent.com/15127974/66472405-da007300-ea95-11e9-8de3-c88c77b83936.png">

**Comment by nikivdev** [comment]
Posted on [forum](https://www.alfredforum.com/topic/13809-macos-catalina-cannot-open-alfred-workflows/), perhaps someone has a solution.

**Comment by vitorgalvao** [comment]
> If you go to Security & Privacy and system prefs, it sometimes gets a prompt here you have to accept

That’s for allowing blocked Kernel Extensions.

> Moreover, I have **"Allow apps downloaded from:"** set to **"Anywhere"**

You really shouldn’t; `App Store and identified developers` is generally enough. Any app that doesn’t work with that, you can right-click and chose `Open`. I’m unsure if that works with compiled binaries in Catalina.

**Comment by skibitsky** [comment]
[This](https://github.com/deanishe/alfred-sublime-text/issues/20#issuecomment-539578934) fixed the issue for me. Thank you, @nikitavoloboev
